<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>NuGetCooldown</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NuGetCooldown.Tests" />
  </ItemGroup>

</Project>
